
    addpath('/Users/nbartlow/MATLAB_tools/YoMesh')  
    addpath('/Users/nbartlow/MATLAB_tools')    
    addpath('/Users/nbartlow/MATLAB_tools/matools')
    addpath('/Users/nbartlow/MATLAB_tools/filter_tools')
    addpath('/Users/nbartlow/MATLAB_tools/objects')
    addpath('/Users/nbartlow/MATLAB_tools/rot_subs')
	addpath('/Users/nbartlow/MATLAB_tools/TriDisloc/')
    addpath('/Users/nbartlow/MATLAB_tools/tridisloc3d/')
    addpath('/Users/nbartlow/NZCode/velk/')
    addpath('/Users/nbartlow/MATLAB_tools/geodesy')